class Scs0009PyController:
    def __init__(self, serial_port: str, baudrate: int = ..., timeout: float = ...) -> None: ...
    def write_torque_enable(self, servo_id: int, mode: int) -> None: ...
    def write_goal_speed(self, servo_id: int, speed: int) -> None: ...
    def write_goal_position(self, servo_id: int, position: float) -> None: ...
    def read_present_position(self, servo_id: int) -> float: ...
    def sync_write_raw_goal_position(self, ids: list[int], positions: list[int]) -> None: ...
